# Generated by Django 4.0.5 on 2022-07-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingrediants', models.TextField(max_length=200)),
                ('process', models.TextField(max_length=200)),
            ],
        ),
    ]
